version: '2.1'

services:
  builder:
    build:
      context: ./
    stdin_open: true
    tty: true
    volumes:
      - './conf/:/app/conf/'
      - './input/:/app/input/'
      - './output/:/app/output/'
